baseURL = 'https://maxofbritton.com/cookbook'
languageCode = 'en-us'
title = 'cookbook'
copyright = "© Maximilian Britton"
theme = "risotto"

[params]

    [params.theme]
    palette = "gooey"
    mode = "dark-mode"

    # Sidebar: about/bio
    [params.about]
    title = "Making with Max"
    description = "I sometimes cooks things."

    # Sidebar: social links
    # Available icon sets:
    # * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
    # * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[menu]

  [[menu.main]]
    identifier = "recipies"
    name = "recipies"
    url = "/recipies/"
    weight = 9

  [[menu.main]]
    identifier = "maxofbritton"
    name = "maxofbritton"
    url = "https://maxofbritton.com/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
